CHANNEL_MAPPING = {'C4:M1': 'eeg',
                'C3:M2': 'eeg',
                'O2:M1': 'eeg',
                'O1:M2': 'eeg',
                'ECG 2': 'ecg',
                'E1:M2': 'eog',
                'E2:M2': 'eog',
                'EMG': 'emg',
                'SPO2': 'misc',
                'PLMr': 'misc',
                'Snore': 'misc',
                'Pressure Snore': 'misc',
                'Pulse': 'misc',
                'Pleth': 'misc',
                'Pos.': 'misc',
                'Light': 'misc',
                'Sum Effort': 'resp',
                'Abdomen': 'resp',
                'Pressure Flow': 'misc',
                'Flow Th': 'temperature',      
                'Thorax': 'misc',
                'Battery': 'misc',
    }
LABEL_MAPPING = {  
    "W": 0,
    "N1": 1,
    "N2": 2,
    "N3": 3,
    "R": 4,
}